"""Make address nullable in teachers

Revision ID: aaaa1111bbbb2222
Revises: 3f5f6f7937c8
Create Date: 2026-05-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aaaa1111bbbb2222'
down_revision: Union[str, None] = '3f5f6f7937c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'address',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'address',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
