"""Make optional teacher fields nullable in database

Revision ID: bbbb2222cccc3333
Revises: aaaa1111bbbb2222
Create Date: 2026-05-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bbbb2222cccc3333'
down_revision: Union[str, None] = 'aaaa1111bbbb2222'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'date_of_birth',
               existing_type=sa.Date(),
               nullable=True)
    op.alter_column('teachers', 'gender',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'blood_group',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'mobile_number',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'religion',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'caste',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'rci_number',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'rci_renewal_date',
               existing_type=sa.Date(),
               nullable=True)
    op.alter_column('teachers', 'qualifications_details',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('teachers', 'category',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('teachers', 'category',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'qualifications_details',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'rci_renewal_date',
               existing_type=sa.Date(),
               nullable=False)
    op.alter_column('teachers', 'rci_number',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'caste',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'religion',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'mobile_number',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'blood_group',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'gender',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('teachers', 'date_of_birth',
               existing_type=sa.Date(),
               nullable=False)
    # ### end Alembic commands ###
