"""Make optional therapist fields nullable in database

Revision ID: cccc3333dddd4444
Revises: bbbb2222cccc3333
Create Date: 2026-05-18 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cccc3333dddd4444'
down_revision: Union[str, None] = 'bbbb2222cccc3333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapists', 'address',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'date_of_birth',
               existing_type=sa.Date(),
               nullable=True)
    op.alter_column('therapists', 'gender',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'blood_group',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'mobile_number',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'religion',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'caste',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'rci_number',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'rci_renewal_date',
               existing_type=sa.Date(),
               nullable=True)
    op.alter_column('therapists', 'qualifications_details',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'category',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'email',
               existing_type=sa.String(),
               nullable=True)
    op.alter_column('therapists', 'specialization',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('therapists', 'specialization',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'email',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'category',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'qualifications_details',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'rci_renewal_date',
               existing_type=sa.Date(),
               nullable=False)
    op.alter_column('therapists', 'rci_number',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'caste',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'religion',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'mobile_number',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'blood_group',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'gender',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('therapists', 'date_of_birth',
               existing_type=sa.Date(),
               nullable=False)
    op.alter_column('therapists', 'address',
               existing_type=sa.String(),
               nullable=False)
    # ### end Alembic commands ###
