"""add clinical fields to therapy reports

Revision ID: f4b754419606
Revises: 7ab58a691691
Create Date: 2026-05-15 15:46:04.621314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f4b754419606'
down_revision: Union[str, None] = '7ab58a691691'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_therapy_reports_student_id', table_name='therapy_reports')
    op.drop_index('ix_therapy_reports_teacher_id', table_name='therapy_reports')
    op.drop_table('therapy_reports')
    op.drop_index('ix_shared_reports_parent_id', table_name='shared_reports')
    op.drop_index('ix_shared_reports_student_id', table_name='shared_reports')
    op.drop_table('shared_reports')
    op.drop_index('ix_parent_students_id', table_name='parent_students')
    op.drop_index('ix_parent_students_parent_id', table_name='parent_students')
    op.drop_index('ix_parent_students_student_id', table_name='parent_students')
    op.drop_table('parent_students')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.alter_column('notifications', 'is_read',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_table('parent_students',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='parent_students_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='parent_students_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='parent_students_pkey'),
    sa.UniqueConstraint('parent_id', 'student_id', name='uq_parent_student')
    )
    op.create_index('ix_parent_students_student_id', 'parent_students', ['student_id'], unique=False)
    op.create_index('ix_parent_students_parent_id', 'parent_students', ['parent_id'], unique=False)
    op.create_index('ix_parent_students_id', 'parent_students', ['id'], unique=False)
    op.create_table('shared_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('therapy_report_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('parent_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('shared_by_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ai_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ai_summary_translated', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('shared_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['users.id'], name='shared_reports_parent_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_id'], ['users.id'], name='shared_reports_shared_by_id_fkey', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='shared_reports_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='shared_reports_pkey'),
    sa.UniqueConstraint('therapy_report_id', 'parent_id', name='uq_report_parent')
    )
    op.create_index('ix_shared_reports_student_id', 'shared_reports', ['student_id'], unique=False)
    op.create_index('ix_shared_reports_parent_id', 'shared_reports', ['parent_id'], unique=False)
    op.create_table('therapy_reports',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('report_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('therapy_type', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('progress_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('goals_achieved', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('progress_level', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='therapy_reports_student_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], name='therapy_reports_teacher_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='therapy_reports_pkey')
    )
    op.create_index('ix_therapy_reports_teacher_id', 'therapy_reports', ['teacher_id'], unique=False)
    op.create_index('ix_therapy_reports_student_id', 'therapy_reports', ['student_id'], unique=False)
    # ### end Alembic commands ###
